### ISSUE TITLE
False "Unsupported OS error" when running on Mac

### ISSUE THREAD

**Issue by Oreotrephes** [cszang/pdsi#1]
Running pdsi() on a mac returns "Error in pdsi(12, 50, muc.clim, 1960, 2000) : Unsupported OS"; the problem seems to be that the function expects Sys.info()["sysname"] to return "Mac" when it in fact returns "Darwin".

**Comment by cszang** [comment]
Thanks for reporting, I do not have a Mac anymore, so I could not check.

**Comment by Oreotrephes** [comment]
Thanks very much for the package!

I'm still trying to find a concise explanation of exactly how the PDSI
algorithm works; the original publication is so dense...

**Comment by cszang** [comment]
;-) this is unfortunately very true, and the major reason keeping me from implementing it directly in R...
