### ISSUE TITLE
bootRes issue

### ISSUE THREAD

**Issue by khufkens** [cszang/pdsi#3]
Quits on a missing bootRes required package (on loading), which is easily resolved by installing it. Might want to add a proper warning. Had a ton of questions from people not knowing what to do with similar errors.

Otherwise, saved my day on calculating PDSI. Thanks a million!

> Downloading github repo cszang/pdsi@master
> Installing pdsi 
> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore >CMD INSTALL  \
> '/private/var/folders/ll/kg6krgsn6sb29k59ts8ntl080000gn/T/RtmpmOyEAp/devtools4b4319288ce7/cszang-pdsi-6b8d279'  \
>  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library' --install-tests 
> - installing _source_ package ‘pdsi’ ...
>   *\* R
>   *\* exec
>   *\* inst
>   *\* preparing package for lazy loading
>   Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
>   there is no package called ‘bootRes’
>   ERROR: lazy loading failed for package ‘pdsi’
> - removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/pdsi’
>   Error: Command failed (1)

**Comment by cszang** [comment]
Thanks - I added bootRes to depends, so it will install automatically when using devtools::install_github()
